### ISSUE TITLE
Server crash when connecting a hose to a sprinkler in 1.11.2

### ISSUE THREAD

**Issue by thejims** [McJty/AquaMunda#5]
Server instantly crashed when right clicking a hose on a sprinkler, repeat crashes on restarts

Crash pastebin:
http://pastebin.com/ScDpg1Mc

Crash snippet:
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at mcjty.aquamunda.immcraft.LiquidCableHandler.tick(LiquidCableHandler.java:30)
        at mcjty.immcraft.blocks.bundle.BundleTE.lambda$update$0(BundleTE.java:43)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at mcjty.immcraft.blocks.bundle.BundleTE.func_73660_a(BundleTE.java:43)
        at net.minecraft.world.World.func_72939_s(World.java:1801)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
        at java.lang.Thread.run(Thread.java:745)

**Comment by McJty** [comment]
Sorry for the slow reaction. Was very busy with other things. I'll try to check this out

**Comment by McJty** [comment]
Fixed next release
